[versions]
agp = "9.1.1"
alonlib = "1.0.5"
kotlin = "2.4.20"
ftc-sdk = "12.0.0"
dashboard = "0.5.1"
roadrunner-core = "1.0.1"
roadrunner-ftc = "0.1.25"
appcompat = "1.8.0"
core-ktx = "1.19.0"

# SDK Versions
compileSdk = "37"
minSdk = "36"
#noinspection OldTargetApi,ExpiredTargetSdkVersion
targetSdk = "36"

[libraries]
alonlib = { module = "com.github.alonHamb:AlonLib", version.ref = "alonlib" }

# FTC SDK
ftc-inspection = { group = "org.firstinspires.ftc", name = "Inspection", version.ref = "ftc-sdk" }
ftc-blocks = { group = "org.firstinspires.ftc", name = "Blocks", version.ref = "ftc-sdk" }
ftc-robotcore = { group = "org.firstinspires.ftc", name = "RobotCore", version.ref = "ftc-sdk" }
ftc-robotserver = { group = "org.firstinspires.ftc", name = "RobotServer", version.ref = "ftc-sdk" }
ftc-onbotjava = { group = "org.firstinspires.ftc", name = "OnBotJava", version.ref = "ftc-sdk" }
ftc-hardware = { group = "org.firstinspires.ftc", name = "Hardware", version.ref = "ftc-sdk" }
ftc-ftccommon = { group = "org.firstinspires.ftc", name = "FtcCommon", version.ref = "ftc-sdk" }
ftc-vision = { group = "org.firstinspires.ftc", name = "Vision", version.ref = "ftc-sdk" }

# Dashboard
acmerobotics-dashboard = { group = "com.acmerobotics.dashboard", name = "dashboard", version.ref = "dashboard" }

# RoadRunner
roadrunner-core = { group = "com.acmerobotics.roadrunner", name = "core", version.ref = "roadrunner-core" }
roadrunner-actions = { group = "com.acmerobotics.roadrunner", name = "actions", version.ref = "roadrunner-core" }
roadrunner-ftc = { group = "com.acmerobotics.roadrunner", name = "ftc", version.ref = "roadrunner-ftc" }

# AndroidX
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

[bundles]
ftc-sdk = [
    "ftc-inspection",
    "ftc-blocks",
    "ftc-robotcore",
    "ftc-robotserver",
    "ftc-onbotjava",
    "ftc-hardware",
    "ftc-ftccommon",
    "ftc-vision"
]
roadrunner = [
    "roadrunner-core",
    "roadrunner-actions",
    "roadrunner-ftc"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
